#!/bin/bash

here=$(pwd)

# if RPi
# need spi_serial, PIL, Adafruit_GPIO, Adafruit SSD1306


# get spi_serial and install
echo "**INSTALLING SPI_SERIAL"

reset_spi_serial.py




apt-get update
apt-get install build-essential python-pip python-dev python-imaging python-smbus git

# get Adafruit_GPIO
if $(python -c "import Adafruit_GPIO"
echo "**INSTALLING ADAFRUIT_GPIO"
git clone https://github.com/adafruit/Adafruit_Python_GPIO.git libs/Adafruit_Python_GPIO 
cd libs/Adafruit_Python_GPIO
python setup.py install
cd $here
fi

# get PIL and install
echo "**INSTALLING PIL"
pip install pillow

# get Adafruit_SSD1306
echo "**INSTALLING RPi.GPIO"
pip install RPi.GPIO
git clone https://github.com/adafruit/Adafruit_Python_SSD1306.git libs/Adafruit_Python_SSD1306
cd libs/Adafruit_Python_SSD1306
python setup.py install
cd $here

# run shapes
echo "**RUNNING shapes.py"
echo "You should see some shapes and a hello world message on your screen."
python shapes.py
#if Edison


#end if

# run cc1110 test
echo "**RUNNING cc1110_set_leds.py"
echo "You should see the two Explorer LEDs blink, then stay on."
python cc1110_set_leds.py
